### ISSUE TITLE
App crashes on launching from background after some time

### ISSUE THREAD

**Issue by kriticalflare** [gargakshit/readit#1]
version: 1.0.1
OS version: Android 10 
adb logcat:
```
2020-02-13 15:08:49.191 1520-3100/? I/ActivityManager: Process garg.akshit.paperplane.readit (pid 4063) has died: cch+60 CAC 
2020-02-13 15:09:06.974 1520-8889/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=garg.akshit.paperplane.readit/.MainActivity bnds=[236,77][439,397]} from uid 10106
2020-02-13 15:09:07.582 7509-7509/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: garg.akshit.paperplane.readit, PID: 7509
    java.lang.RuntimeException: Parcel android.os.Parcel@8980c51: Unmarshalling unknown type code 7536745 at offset 104
        at android.os.Parcel.readValue(Parcel.java:2945)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3327)
        at android.os.Parcel.readSparseArray(Parcel.java:2484)
        at android.os.Parcel.readValue(Parcel.java:2923)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1029)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2156)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1569)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1522)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1353)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3310)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-02-13 15:09:07.585 1520-8019/? W/ActivityTaskManager:   Force finishing activity garg.akshit.paperplane.readit/.MainActivity
2020-02-13 15:09:07.627 1520-8889/? I/ActivityManager: Process garg.akshit.paperplane.readit (pid 7509) has died: vis+99 TOP 

```

**Comment by gargakshit** [comment]
Hey @kriticalflare 
Could you please provide me with the steps to reproduce, as my testers and me have no such issues. 

Devices we tested on:
Android emulator: Android 10
Mi A2: Android 10
Samsung Galaxy S9: Android 10
Mi A1: Android 9

**Comment by kriticalflare** [comment]
You can reproduce it easily , keep the app open in background and then try to get the system to kill it in background. Open numerous apps to trigger the system OOM killer. When you will later open the app from recents it will crash. 100% reproducible on my end from a release build , that's how I got the logs.

**Comment by gargakshit** [comment]
> You can reproduce it easily , keep the app open in background and then try to get the system to kill it in background. Open numerous apps to trigger the system OOM killer. When you will later open the app from recents it will crash. 100% reproducible on my end from a release build , that's how I got the logs.

Thanks. I'll try.

**Comment by gargakshit** [comment]
Yes the issue is reproducible. I will look into the issue after my exams. Thanks for reporting :)

**Comment by gargakshit** [comment]
Thanks for the fix @kriticalflare :)
